name: CI

on:
  push:
    branches:
      - '9.4.x'
      - '10.0.x'
      - '11.0.x'
      - '12.1.x'
  pull_request:

jobs:
  build:
    name: Build
    uses: jetty/.github/.github/workflows/maven-ci.yml@main
    with:
      jdk-matrix: '[ "17", "21" ]'
